# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/fastlane/docs
# All available actions: https://docs.fastlane.tools/actions
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "2.212.0"

default_platform :android

platform :android do
  def generate_changelog
    tag = sh("git describe --tags --abbrev=0 @^ 2>/dev/null || echo ''").strip
    if tag.empty?
      log_command = 'git --no-pager log --pretty=format:"%s" --no-merges --reverse'
    else
      log_command = "git --no-pager log --pretty=format:\"%s\" --no-merges #{tag}..@ --reverse"
    end
    sh(log_command).strip
  end

  desc "Submit a new build to Firebase App Distribution"
  lane :deploy_firebase do |options|
    apk_path = options[:apk_path]
    UI.user_error!("apk_path is required for deploy_firebase lane") unless apk_path

    firebase_app_id = options[:firebase_app_id]
    UI.user_error!("firebase_app_id is required for deploy_firebase lane") unless firebase_app_id

    credentials_path = options[:credentials_path]
    UI.user_error!("credentials_path is required for deploy_firebase lane") unless credentials_path

    groups = options[:groups]
    UI.user_error!("groups is required for deploy_firebase lane") unless groups

    changelog = generate_changelog

    firebase_app_distribution(
      app: firebase_app_id,
      groups: groups,
      release_notes: changelog,
      apk_path: apk_path,
      service_credentials_file: credentials_path
    )
  end


  desc "Submit a new build to Google Play Internal"
  lane :deploy_play_internal do |options|
    aab_path = options[:aab_path]
    UI.user_error!("aab_path is required for deploy_play_internal lane") unless aab_path

    json_key_path = options[:json_key_path]
    UI.user_error!("json_key_path is required for deploy_play_internal lane") unless json_key_path

    version_code = options[:version_code]
    UI.user_error!("version_code is required for deploy_play_internal lane") unless version_code

    version_name_suffix = options[:version_name_suffix]
    UI.user_error!("version_name_suffix is required for deploy_play_internal lane") unless version_name_suffix

    changelog = "🌓 Nightly build #{version_name_suffix} (#{version_code})"

    metadata_base_dir = File.expand_path("metadata/android", File.dirname(__FILE__))
    locale = "en-US"
    changelog_dir = File.join(metadata_base_dir, locale, "changelogs")
    FileUtils.mkdir_p(changelog_dir)
    File.write(File.join(changelog_dir, "#{version_code}.txt"), changelog)
    File.write(File.join(changelog_dir, "default.txt"), changelog)

    upload_to_play_store(
      package_name: 'com.everlog',
      track: 'internal',
      json_key: json_key_path,
      aab: aab_path,
      metadata_path: metadata_base_dir
    )
  end

  desc "Submit a new build to Google Play Release"
  lane :deploy_play_release do |options|
    aab_path = options[:aab_path]
    UI.user_error!("aab_path is required for deploy_play_release lane") unless aab_path

    json_key_path = options[:json_key_path]
    UI.user_error!("json_key_path is required for deploy_play_release lane") unless json_key_path

    version_code = options[:version_code]
    UI.user_error!("version_code is required for deploy_play_release lane") unless version_code

    changelog = options[:changelog]
    UI.user_error!("changelog is required for deploy_play_release lane") unless changelog

    metadata_base_dir = File.expand_path("metadata/android", File.dirname(__FILE__))
    locale = "en-US"
    changelog_dir = File.join(metadata_base_dir, locale, "changelogs")
    FileUtils.mkdir_p(changelog_dir)
    File.write(File.join(changelog_dir, "#{version_code}.txt"), changelog)

    upload_to_play_store(
      package_name: 'com.everlog',
      track: 'production',
      release_status: 'draft',
      json_key: json_key_path,
      aab: aab_path,
      metadata_path: metadata_base_dir
    )
  end

  error do |lane, exception|
    # Handle errors (e.g. notify Slack)
  end
end



# More information about multiple platforms in fastlane: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Platforms.md
# All available actions: https://docs.fastlane.tools/actions

# fastlane reports which actions are used
# No personal data is sent or shared. Learn more at https://github.com/fastlane/enhancer