# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/fastlane/docs
# All available actions: https://docs.fastlane.tools/actions
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "2.141.0"

default_platform :android

def slack_error(message)
    slack(
        use_webhook_configured_username_and_icon: true,
        username: "Fastlane Android",
        message: message,
        success: false,
        payload: {
            "Build Date" => Time.new.to_s,
            "Built by" => "Fastlane",
            "App version" => @appVersion,
            "Changelog" => @changeLog
        }
    )
end

def slack_success(message, attachment, channel)
    slack(
        use_webhook_configured_username_and_icon: true,
        channel: channel,
        username: "Fastlane Android",
        message: message,
        success: true,
        default_payloads: [],
        payload: {
            "App version" => @appVersion,
        },
        attachment_properties: attachment
    )
end

def gradle_test
    gradle(
        task: "testStagingDebug",
        flags: "--stacktrace"
    )
end

def gradle_assemble_debug
    gradle(
        task: ":mobile:assembleStagingDebug",
        flags: "--stacktrace"
    )
end

def gradle_assemble_rеlease
    gradle(
        task: ":mobile:assembleStagingRelease",
        flags: "--stacktrace"
    )
end

def supply_track(track)
    supply(
        track: track,
        apk: lane_context[SharedValues::GRADLE_APK_OUTPUT_PATH],
        mapping: lane_context[SharedValues::GRADLE_MAPPING_TXT_OUTPUT_PATH]
    )
end

def send_to_firebase_app_distribution
    firebase_app_distribution(
      app: ENV["FIREBASE_APP_ID"],
      groups: "everlog-alpha-testers",
      release_notes: @changeLog,
      firebase_cli_token: ENV["FIREBASE_TOKEN"],
    )
end

def send_to_google_play_internal
    supply_track("internal")
end

platform :android do
    before_all do
        ENV["SLACK_URL"] = "WEBHOOK_URL"
        # Obtain app version
        @appVersion = get_version_name(
            gradle_file_path: "mobile/build.gradle",
            ext_constant_name: "versionName"
        )
        # Obtain changelog
        tag = sh 'echo $(git describe --tags --abbrev=0 @^)'
        logCommand = 'echo "$(git --no-pager log --pretty=format:"☐ %s" ' + tag.strip! + '..@ --reverse)"'
        log = sh logCommand
        # Format
        @changeLog = log
    end

    ################ Testing #################

    desc "Test Slack integration"
    lane :test_slack do
#        slack_error("⚒ This is a drill of Slack errors")
    end

    desc "Test Slack test prompt integration"
    lane :test_slack_success do
#         slack_success(
#            "⚒ This is a drill of Slack success",
#            {
#                fields: [
#                    {
#                        title: "Example changelog",
#                        value: @changeLog
#                    }
#                ]
#            },
#            "#android-robots"
#        )
    end

    ################# Lanes ##################

    desc "Run unit tests"
    lane :test do
        gradle_test
    end

    desc "Submit a new alpha build to Firebase App Distribution"
    lane :deploy_firebase_app_distribution do
        gradle_assemble_debug
        send_to_firebase_app_distribution
#        slack_success(
#            "🚀⚒ New build added to Firebase Beta. Please make sure to test the following in dev",
#            {
#                fields: [
#                    {
#                        title: "Changes to test",
#                        value: @changeLog
#                    }
#                ]
#            },
#            "#android"
#        )
    end

    desc "Deploy a new version to the Google Play internal channel"
    lane :deploy_google_play_internal do
        gradle_assemble_rеlease
        send_to_google_play_internal
#        slack_success(
#            "🚀 Release build is about to be sent to Google Play. Please make sure to go through the Essential App Functionality Checklist in production",
#            {
#                fields: [
#                    {
#                        title: "Login Checklist",
#                        value: "☐ Register a new user \n ☐ Login a new user"
#                    }
#                ]
#            },
#            "#android"
#        )
    end

    ################ Errors #################

    desc "Build a new release version locally"
    lane :build_release_local do
        gradle_test
        gradle_assemble_rеlease
    end

    error do |lane, exception|
#       slack_error("🔥 " + exception.message)
    end
end


# More information about multiple platforms in fastlane: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Platforms.md
# All available actions: https://docs.fastlane.tools/actions

# fastlane reports which actions are used
# No personal data is sent or shared. Learn more at https://github.com/fastlane/enhancer