# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/fastlane/docs
# All available actions: https://docs.fastlane.tools/actions
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "2.212.0"

default_platform :android

platform :android do
  desc "Submit a new build to Firebase App Distribution"
  lane :deploy_firebase do |options|
    apk_path = options[:apk_path]
    UI.user_error!("apk_path is required for deploy_firebase lane") unless apk_path

    firebase_app_id = options[:firebase_app_id]
    UI.user_error!("firebase_app_id is required for deploy_firebase lane") unless firebase_app_id

    credentials_path = options[:credentials_path]
    UI.user_error!("credentials_path is required for deploy_firebase lane") unless credentials_path

    groups = options[:groups]
    UI.user_error!("groups is required for deploy_firebase lane") unless groups

    # Compute changelog
    tag = sh("git describe --tags --abbrev=0 @^ 2>/dev/null || echo ''").strip
    if tag.empty?
      log_command = 'git --no-pager log --pretty=format:"%s" --reverse'
    else
      log_command = "git --no-pager log --pretty=format:\"%s\" #{tag}..@ --reverse"
    end
    changelog = sh(log_command).strip

    # Upload to Firebase
    firebase_app_distribution(
      app: firebase_app_id,
      groups: groups,
      release_notes: changelog,
      apk_path: apk_path,
      service_credentials_file: credentials_path
    )
  end

  error do |lane, exception|
    # Handle errors (e.g. notify Slack)
  end
end



# More information about multiple platforms in fastlane: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Platforms.md
# All available actions: https://docs.fastlane.tools/actions

# fastlane reports which actions are used
# No personal data is sent or shared. Learn more at https://github.com/fastlane/enhancer