name: 'build-android'
inputs:
  ciVersionCode:
    description: 'Version code to use for the build'
    required: true
runs:
  using: "composite"
  steps:
    - name: Set up Gradle
      uses: ./.github/actions/setup-gradle
    - name: Build Android
      shell: bash
      run: |
        set -Eeuo pipefail 
        ./gradlew :mobile:assembleDebug ${ciVersionCode:+-PciVersionCode=$ciVersionCode}
      env:
        ciVersionCode: ${{ inputs.ciVersionCode }}
    - name: Artifacts
      uses: actions/upload-artifact@v7
      if: always() # Ensure all artifacts are collected, even after errors
      with:
        name: Android Build
        path: |
          **/*.apk
          **/build
          **/secrets.properties
          **/google-services.json
          **/google-deployment-key.json
          **/*.keystore
          **/*.jks