name: nightly-check

on:
  schedule:
    - cron: '0 0 * * *'

env:
  E2E_TEST_USER_EMAIL: ${{ secrets.E2E_TEST_USER_EMAIL }}
  E2E_TEST_USER_PASSWORD: ${{ secrets.E2E_TEST_USER_PASSWORD }}
  MONITORING_SLACK_URL: ${{ secrets.MONITORING_SLACK_URL }}
  GOOGLE_SERVICES_DEV_JSON: ${{ secrets.GOOGLE_SERVICES_DEV_JSON }}
  GOOGLE_SERVICES_PROD_JSON: ${{ secrets.GOOGLE_SERVICES_PROD_JSON }}
  KEYSTORE_DEBUG_BASE64: ${{ secrets.KEYSTORE_DEBUG_BASE64 }}
  KEYSTORE_RELEASE_BASE64: ${{ secrets.KEYSTORE_RELEASE_BASE64 }}

jobs:
  unit-test:
    runs-on: ubuntu-24.04
    permissions:
      checks: write
    concurrency:
      group: ${{ github.ref }}-unit-test
      cancel-in-progress: true
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Test
        uses: ./.github/actions/unit-test
      - name: Slack report
        uses: slackapi/slack-github-action@v3
        if: always() # Ensure report is sent, even after errors
        with:
          payload: |
            {
              "text": "🌓️️ Nightly job <${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|${{ github.job }}> ${{ job.status }}"
            }
          webhook: ${{ env.MONITORING_SLACK_URL }}
          webhook-type: incoming-webhook

  build-android:
    runs-on: ubuntu-24.04
    concurrency:
      group: ${{ github.ref }}-build-android
      cancel-in-progress: true
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Build Android
        uses: ./.github/actions/build-android
      - name: Slack report
        uses: slackapi/slack-github-action@v3
        if: always() # Ensure report is sent, even after errors
        with:
          payload: |
            {
              "text": "🌓️️ Nightly job <${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|${{ github.job }}> ${{ job.status }}"
            }
          webhook: ${{ env.MONITORING_SLACK_URL }}
          webhook-type: incoming-webhook

  test-android:
    runs-on: ubuntu-24.04
    concurrency:
      group: ${{ github.ref }}-test-android
      cancel-in-progress: true
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Test Android
        uses: ./.github/actions/test-android
      - name: Slack report
        uses: slackapi/slack-github-action@v3
        if: always() # Ensure report is sent, even after errors
        with:
          payload: |
            {
              "text": "🌓️️ Nightly job <${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|${{ github.job }}> ${{ job.status }}"
            }
          webhook: ${{ env.MONITORING_SLACK_URL }}
          webhook-type: incoming-webhook
