name: staging-check

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  E2E_TEST_USER_EMAIL: ${{ secrets.E2E_TEST_USER_EMAIL }}
  E2E_TEST_USER_PASSWORD: ${{ secrets.E2E_TEST_USER_PASSWORD }}
  GOOGLE_SERVICES_DEV_JSON: ${{ secrets.GOOGLE_SERVICES_DEV_JSON }}
  GOOGLE_SERVICES_PROD_JSON: ${{ secrets.GOOGLE_SERVICES_PROD_JSON }}
  GOOGLE_DEPLOYMENT_KEY_DEV_JSON: ${{ secrets.GOOGLE_DEPLOYMENT_KEY_DEV_JSON }}
  GOOGLE_DEPLOYMENT_KEY_PROD_JSON: ${{ secrets.GOOGLE_DEPLOYMENT_KEY_PROD_JSON }}
  KEYSTORE_DEBUG_BASE64: ${{ secrets.KEYSTORE_DEBUG_BASE64 }}
  KEYSTORE_RELEASE_BASE64: ${{ secrets.KEYSTORE_RELEASE_BASE64 }}

jobs:
  unit-test:
    runs-on: ubuntu-24.04
    permissions:
      checks: write
    concurrency:
      group: ${{ github.ref }}-unit-test
      cancel-in-progress: true
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Test
        uses: ./.github/actions/unit-test

  build-android:
    runs-on: ubuntu-24.04
    concurrency:
      group: ${{ github.ref }}-build-android
      cancel-in-progress: true
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - name: Build Android
        id: version_logic
        shell: bash
        run: |
          TYPE="staging"
          if [[ "${{ github.event_name }}" == "push" && "${{ github.ref }}" == "refs/heads/master" ]]; then
            TYPE="master"
          fi
          chmod +x ./tools/versioning/version_code.sh
          VERSION_CODE=$(./tools/versioning/version_code.sh $TYPE)
          echo "VERSION_CODE=$VERSION_CODE" >> $GITHUB_OUTPUT
          echo "### Version Code: $VERSION_CODE" >> $GITHUB_STEP_SUMMARY
        
      - name: Build Android
        uses: ./.github/actions/build-android
        with:
          ciVersionCode: ${{ steps.version_logic.outputs.VERSION_CODE }}

  deploy-android-staging:
    needs: [build-android]
    runs-on: ubuntu-24.04
    concurrency:
      group: ${{ github.ref }}-deploy-android-staging
      cancel-in-progress: true
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'
          bundler-cache: true
      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          name: Android Build
      - name: Deploy
        shell: bash
        run: |
          bundle exec fastlane android deploy_firebase \
            apk_path:mobile/build/outputs/apk/debug/mobile-debug.apk \
            firebase_app_id:1:807594467020:android:ac26b664e229fe37 \
            credentials_path:mobile/src/debug/google-deployment-key.json \
            groups:everlog-pr-testers

  test-android:
    runs-on: ubuntu-24.04
    concurrency:
      group: ${{ github.ref }}-test-android
      cancel-in-progress: true
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Test Android
        uses: ./.github/actions/test-android