name: staging-check

on:
  schedule:
    - cron: '0 0 * * *'

env:
  E2E_TEST_USER_EMAIL: ${{ secrets.E2E_TEST_USER_EMAIL }}
  E2E_TEST_USER_PASSWORD: ${{ secrets.E2E_TEST_USER_PASSWORD }}
  GOOGLE_SERVICES_DEV_JSON: ${{ secrets.GOOGLE_SERVICES_DEV_JSON }}
  GOOGLE_SERVICES_PROD_JSON: ${{ secrets.GOOGLE_SERVICES_PROD_JSON }}
  GOOGLE_DEPLOYMENT_KEY_DEV_JSON: ${{ secrets.GOOGLE_DEPLOYMENT_KEY_DEV_JSON }}
  GOOGLE_DEPLOYMENT_KEY_PROD_JSON: ${{ secrets.GOOGLE_DEPLOYMENT_KEY_PROD_JSON }}
  KEYSTORE_DEBUG_BASE64: ${{ secrets.KEYSTORE_DEBUG_BASE64 }}
  KEYSTORE_RELEASE_BASE64: ${{ secrets.KEYSTORE_RELEASE_BASE64 }}
  KEYSTORE_RELEASE_PASSWORD: ${{ secrets.KEYSTORE_RELEASE_PASSWORD }}
  KEYSTORE_RELEASE_ALIAS: ${{ secrets.KEYSTORE_RELEASE_ALIAS }}
  KEYSTORE_RELEASE_ALIAS_PASSWORD: ${{ secrets.KEYSTORE_RELEASE_ALIAS_PASSWORD }}

jobs:
  unit-test:
    runs-on: ubuntu-24.04
    permissions:
      checks: write
    concurrency:
      group: ${{ github.ref }}-unit-test
      cancel-in-progress: true
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Test
        uses: ./.github/actions/unit-test

  build-android:
    runs-on: ubuntu-24.04
    concurrency:
      group: ${{ github.ref }}-build-android
      cancel-in-progress: true
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0 # Do not remove. Needed to compute app version
      - name: Build Android
        id: build_android
        uses: ./.github/actions/build-android
        with:
          buildType: 'debug'
          versionBuildType: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' && 'master' || 'staging' }}

  deploy-android-staging:
    needs: [build-android]
    runs-on: ubuntu-24.04
    concurrency:
      group: ${{ github.ref }}-deploy-android-staging
      cancel-in-progress: true
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0 # Do not remove. Needed to compute changelog
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'
          bundler-cache: true
      - name: Download artifacts
        uses: actions/download-artifact@v8
        with:
          name: Android Build
      - name: Deploy
        shell: bash
        run: |
          bundle exec fastlane android deploy_firebase \
            apk_path:mobile/build/outputs/apk/debug/mobile-debug.apk \
            firebase_app_id:1:807594467020:android:ac26b664e229fe37 \
            credentials_path:mobile/src/debug/google-deployment-key.json \
            groups:everlog-staging-testers

  test-android:
    runs-on: ubuntu-24.04
    concurrency:
      group: ${{ github.ref }}-test-android
      cancel-in-progress: true
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Test Android
        uses: ./.github/actions/test-android